### ISSUE TITLE
[Bug] Resume button selects the bottom chapter instead of the next unread chapter when sorting in reverse

### ISSUE THREAD

**Issue by HouseNewbie** [Suwayomi/Tachidesk-Server#502]
## Device information
- Tachidesk version: v0.7.0-r1197-windows-x64
- Server Operating System: Windows 10
- Server Desktop Environment: N/A
- Server JVM version: no clue
- Client Operating System: <usually the same as above Server Operating System>
- Client Web Browser: Version 110.0.5481.100 (Official Build) (64-bit)

## Steps to reproduce
1. Sort chapter in reverse
2. Click Resume

### Expected behavior
It should resume to the next unread chapter.

### Actual behavior
When sorting chapters in reverse and clicking the 'Resume' button, Tachidesk is not selecting the next unread chapter, but instead selecting the chapter at the bottom of the list.

**Comment by harsh0596** [comment]
im also having this issue
